services:
  notification_producer:
    container_name: notification_producer
    build: .
    env_file:
      - ./src/.env
    restart: always
    networks:
      - movies-network
    command: bash -c "
      alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000"

networks:
  movies-network:
    name: movies-network
    external: true